workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 20
    environment:
      xcode: latest
scripts:
  - name: Build iOS App
    script: |
      xcodebuild -workspace Memorize.xcworkspace \
        -scheme Memorize \
        -sdk iphoneos \
        -configuration Release \
        -archivePath $CM_BUILD_DIR/Memorize.xcarchive \
        -allowProvisioningUpdates \
        archive
    artifacts:
      - $CM_BUILD_DIR/Memorize.xcarchive
    publishing:
      email:
        recipients:
          - sofianadraga10@gmail.com
