workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 20
    environment:
      xcode: latest
    scripts:
      - name: Build and export iOS app
        script: |
          xcodebuild -project Memorize/Memorize.xcodeproj \
            -scheme Memorize \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/Memorize.xcarchive \
            -allowProvisioningUpdates \
            archive

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Memorize.xcarchive \
            -exportOptionsPlist Memorize/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa

    publishing:
      email:
        recipients:
          - sofianadraga10@gmail.com
